PixageStudioWeb/Models/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PixageStudioWeb.Models
{
    public class ContactViewModel
    {
        [Required]
        [StringLength(20, MinimumLength = 5)]
        public string Name { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        public string Subject { get; set; }
        [Required]
        public string Message { get; set; }
    }
}

PixageStudioWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PixageStudioWeb.Data;
using PixageStudioWeb.Models;

namespace PixageStudioWeb.Controllers
{
    
    public class HomeController : Controller
    {
        ApplicationDbContext _context;
        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }
        
     
        public IActionResult Index()
        {
            var cat = _context.Categories.Where(x=>x.Name!="HomePage").OrderBy(x=>x.Name).ToList();
            var Img = from images in _context.ImagePools
                      join category in _context.Categories on images.CategoryId equals category.Id
                      where (category.Name.Equals("HomePage"))
                      select images;
            ViewBag.Category = cat.ToList();
            ViewBag.Carousel = Img.ToList();
            return View();
        }
        public IActionResult GetGenres(int id)
        {
            ViewBag.Category = _context.Categories.Where(x=>x.Name!="HomePage").OrderBy(x=>x.Name).ToList();
            ViewBag.Images = _context.ImagePools.Where(x=>x.CategoryId == id).ToList();
            return PartialView("~/Views/Home/_PortfolioPartial.cshtml");
        }
        
        public IActionResult About()
        {
           
            ViewBag.Category = _context.Categories.Where(x=>x.Name!="HomePage").OrderBy(x=>x.Name).ToList();
            ViewBag.AboutImage = from image in _context.ImagePools 
                                 join  category in _context.Categories on image.CategoryId equals category.Id
                                 where (category.Name.Equals("AboutUs") && image.Status ==true)
                                 select image;
            return View();
        }

        public IActionResult Contact(ContactViewModel vm)
        {
           
            ViewBag.Category = _context.Categories.Where(x=>x.Name!="HomePage").OrderBy(x=>x.Name).ToList();
            if (ModelState.IsValid)
            {
                try
                {
                    MailMessage msz = new MailMessage();
                    msz.From = new MailAddress(vm.Email);//Email which you are getting 
                                                         //from contact us page 
                    msz.To.Add("prabhakaraninbox@gmail.com");//Where mail will be sent 
                    msz.Subject = vm.Subject;
                    msz.Body = vm.Message;
                    SmtpClient smtp = new SmtpClient();

                    smtp.Host = "smtp.gmail.com";

                    smtp.Port = 587;

                    smtp.Credentials = new System.Net.NetworkCredential
                    ("prabharkaraninbox@gmail.com", "password");

                    smtp.EnableSsl = true;

                    smtp.Send(msz);

                    ModelState.Clear();
                    ViewBag.Message = "Thank you for Contacting us ";
                }
                catch (Exception ex)
                {
                    ModelState.Clear();
                    ViewBag.Message = $" Sorry we are facing Problem here {ex.Message}";
                }
            }

            return View();
        }
      
       
       

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PixageStudioWeb/Controllers/ImagePoolsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PixageStudioWeb.Data;
using PixageStudioWeb.Models;

namespace PixageStudioWeb.Controllers
{
    //[Authorize(Roles="Administrator, Editor")]
    public class ImagePoolsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _he;
        public ImagePoolsController(ApplicationDbContext context, IHostingEnvironment he)
        {
            _he = he;
            _context = context;
        }

        // GET: ImagePools
        public async Task<IActionResult> Index()
        {
            ViewBag.ImageList = await _context.ImagePools.OrderBy(x=>x.CategoryId).OrderBy(x=>x.AltName).ToListAsync();
            return View();
        }



        // GET: ImagePools/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var imagePool = await _context.ImagePools
                .FirstOrDefaultAsync(m => m.Id == id);
            if (imagePool == null)
            {
                return NotFound();
            }

            return View(imagePool);
        }
        public ActionResult SetAboutPicture(int id, ImagePool imagePool)
        {
            if (id != imagePool.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if(imagePool.Status==false)
                    {
                        imagePool.Status = true;
                      
                        
                    }
                    else
                    {
                        imagePool.Status = false;
                    }

                    _context.Update(imagePool);
                   
                     _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImagePoolExists(imagePool.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(imagePool);
        }

        [HttpPost]
        public async Task<IActionResult> UploadFile(IFormFile file, int genre)
        {
            ImagePool Images = new ImagePool();
            if (file == null || file.Length == 0)
                return Content("file not selected");

            var path = Path.Combine(Directory.GetCurrentDirectory(),
                                    "wwwroot/Images",
                                    file.FileName);

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await file.CopyToAsync(stream);
                Images.AltName = file.FileName;
                Images.ImagePath = path;
                Images.CategoryId = genre;
                _context.Add(Images);
                _context.SaveChanges();
            }

            return RedirectToAction("Upload", "Admin");
        }
        [HttpPost]
        public async Task<IActionResult> UploadMultiple(ICollection<IFormFile> files, int genre)
        {
            
            
            foreach (var file in files)

            {
                ImagePool Images = new ImagePool();

                var path = Path.Combine(Directory.GetCurrentDirectory(),
                                    "wwwroot/Images",
                                    file.FileName);
                if (file.Length > 0)
                {
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(fileStream);
                        Images.AltName = file.FileName;
                        Images.ImagePath = path;
                        Images.CategoryId = genre;
                        _context.Add(Images);
                        _context.SaveChanges();
                    }
                }
            }
           
            return RedirectToAction("Upload", "Admin");
        }
        
        private string GetContentType(string path)
        {
            throw new NotImplementedException();
        }

        // GET: ImagePools/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ImagePools/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AltName,ImgData,Genre")] ImagePool imagePool)
        {
            if (ModelState.IsValid)
            {
                _context.Add(imagePool);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(imagePool);
        }

        // GET: ImagePools/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var imagePool = await _context.ImagePools.FindAsync(id);
            if (imagePool == null)
            {
                return NotFound();
            }
            return View(imagePool);
        }

        // POST: ImagePools/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AltName,ImgData,Genre,Status")] ImagePool imagePool)
        {
            if (id != imagePool.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   
                    _context.Update(imagePool);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImagePoolExists(imagePool.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(imagePool);
        }

        // GET: ImagePools/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var imagePool = await _context.ImagePools
                .FirstOrDefaultAsync(m => m.Id == id);
            if (imagePool == null)
            {
                return NotFound();
            }

            return View(imagePool);
        }

        // POST: ImagePools/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ViewBag.deleteSuccess = "false";

            var imagePool = await _context.ImagePools
               .FirstOrDefaultAsync(m => m.Id == id);
            var fullPath = imagePool.ImagePath.ToString();

            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
                ViewBag.deleteSuccess = "true";
            }
            var imagePools = await _context.ImagePools.FindAsync(id);
            _context.ImagePools.Remove(imagePools);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        

        private bool ImagePoolExists(int id)
        {
            return _context.ImagePools.Any(e => e.Id == id);
        }
    }
}

PixageStudioWeb/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PixageStudioWeb.Data;
using PixageStudioWeb.Models;

namespace PixageStudioWeb.Controllers
{
    public class PagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        public PagesController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            ViewBag.Images = _context.ImagePools.ToList();
            ViewBag.Category = _context.Categories.Where(x => x.Name != "HomePage").OrderBy(x=>x.Name).ToList();
            return View();
        }
        public IActionResult GetGenre(int id)
        {
            ViewBag.Category = _context.Categories.Where(x=>x.Name!="HomePage").OrderBy(x=>x.Name).ToList();
           
            ViewBag.Genres = _context.ImagePools.Where(x=>x.CategoryId==id);
            return View();
        }
        
    }
}

PixageStudioWeb/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
    <link rel="stylesheet" href="~/Plugin/css/login.css">
<style>
    #about-image
    {
        margin-top:auto;
        border: 3px solid black;
        min-height:300px;
        min-width:200px;
        max-height:300px;
        max-width:200px;
    }
    .about-content{
        margin-top:auto;
        border: 3px solid black;
        min-height:300px;
    }
</style>
<div class="container">
    <div class="col-md-3 about-image">
        @foreach(ImagePool item in ViewBag.AboutImage)
        {
            <img src="~/images/@item.AltName" id="about-image">
        }
        @if (User.IsInRole("Editor") || User.IsInRole("Administrator"))
        {
        <form asp-controller="ImagePools" asp-action="UploadAbout" method="post"
              enctype="multipart/form-data">
            <div class="form-group"><input type="file" name="file" accept="image/*" /></div>
            
            <div class="form-group"><button class="btn btn-primary" type="submit">Upload</button></div>

        </form>
        }
    </div>
    <div class="about-content col-md-7">

    </div>
    <div class="container"></div>
</div>

PixageStudioWeb/Views/Home/Contact.cshtml
@model ContactViewModel
@{
    ViewData["Title"] = "Contact Us";
}

<link rel="stylesheet" href="~/css/site.css" />
<style>
.text-danger{
    display:none;
}
</style>
<div>
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div>

            <div>
                <div class="text-danger" asp-validation-summary="All"></div>
                <form method="post" asp-action="Contact" asp-controller="Home">
                    <div class="form-group">
                        <label asp-for="Name">Name</label>
                        <input asp-for="Name" class="form-control" />

                    </div>
                    <div class="form-group">
                        <label asp-for="Email">Email</label>
                        <input asp-for="Email" class="form-control" />

                    </div>
                    <div class="form-group">
                        <label asp-for="Subject">Subject</label>
                        <input asp-for="Subject" class="form-control" />

                    </div>
                    <div class="form-group">
                        <label asp-for="Message">Message</label>
                        <textarea rows="5" cols="15"
                                  asp-for="Message" class="form-control"></textarea>
                    </div>
                    <div>
                        <button type="submit"
                                class="btn btn-success">
                            Send
                        </button>
                    </div>

                </form>
            </div>

        </div>

        <div>
            <div class="col-md-3"></div>
            <div>
                @if (ViewBag.Message != null)
                {
                    <div>@ViewBag.Message</div>


                }
            </div>
        </div>
    </div>

</div>
@section scripts{
    }

PixageStudioWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";


}




<div id="carousel" style="align-self:center; align-content:center;">
    @foreach (ImagePool item in ViewBag.Carousel)
    {
        <a href="#"><img src="~/images/@Html.DisplayFor(modelItem=> item.AltName)" id="item-1" style="z-index:-1;" /></a>
    }


</div>
<script type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>
<script type="text/javascript" src="~/Plugin/js/jquery.waterwheelCarousel.js"></script>
<script type="text/javascript">
    var $k = jQuery.noConflict();
    $k(document).ready(function () {
        var carousel = $k("#carousel").waterwheelCarousel({
            flankingItems: 3,
            movingToCenter: function ($kitem) {
                $k('#callback-output').prepend('movingToCenter: ' + $kitem.attr('id') + '<br/>');
            },
            movedToCenter: function ($kitem) {
                $k('#callback-output').prepend('movedToCenter: ' + $kitem.attr('id') + '<br/>');
            },
            movingFromCenter: function ($kitem) {
                $k('#callback-output').prepend('movingFromCenter: ' + $kitem.attr('id') + '<br/>');
            },
            movedFromCenter: function ($kitem) {
                $k('#callback-output').prepend('movedFromCenter: ' + $kitem.attr('id') + '<br/>');
            },
            clickedCenter: function ($kitem) {
                $k('#callback-output').prepend('clickedCenter: ' + $kitem.attr('id') + '<br/>');
            }
        });

        $k('#prev').bind('click', function () {
            carousel.prev();
            return false
        });

        $k('#next').bind('click', function () {
            carousel.next();
            return false;
        });

        $k('#reload').bind('click', function () {
            newOptions = eval("(" + $k('#newoptions').val() + ")");
            carousel.reload(newOptions);
            return false;
        });
        $k('body').on('mousewheel', function (e) {
            if (e.originalEvent.wheelDelta > 0) {
                carousel.prev();
                return false;
            }
            else {
                carousel.next();
                return false;
            }
        });


    });
</script>

PixageStudioWeb/Views/Home/_CarouselPartial.cshtml
<style type="text/css">
    body {
        font-family: Arial;
        font-size: 12px;
        background: #ededed;
    }

    .example-desc {
        margin: 3px 0;
        padding: 5px;
    }

    #carousel {
        width: 960px;
        border: 1px solid #222;
        height: 300px;
        background: #FFF;
    }

        #carousel img {
            visibility: hidden; /* hide images until carousel can handle them */
            cursor: pointer; /* otherwise it's not as obvious items can be clicked */
            height:initial;
            width:initial;
        }

    .split-left {
        width: 450px;
        float: left;
    }

    .split-right {
        width: 400px;
        float: left;
        margin-left: 10px;
    }

    #callback-output {
        height: 250px;
        overflow: scroll;
    }

    textarea#newoptions {
        width: 430px;
    }
</style>
<div id="carousel">
    @foreach (ImagePool item in ViewBag.Carousel)
    {
        <a href="#"><img src="~/images/@Html.DisplayFor(modelItem=> item.AltName)" class="image-carousel" style="min-height:700px; min-width:600px;"/></a>
    }
</div>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="~/Plugin/js/jquery.waterwheelCarousel.js"></script>
<script type="text/javascript">
      $(document).ready(function () {
        var carousel = $("#carousel").waterwheelCarousel({
          flankingItems: 3,
          movingToCenter: function ($item) {
            $('#callback-output').prepend('movingToCenter: ' + $item.attr('class') + '<br/>');
          },
          movedToCenter: function ($item) {
            $('#callback-output').prepend('movedToCenter: ' + $item.attr('class') + '<br/>');
          },
          movingFromCenter: function ($item) {
            $('#callback-output').prepend('movingFromCenter: ' + $item.attr('class') + '<br/>');
          },
          movedFromCenter: function ($item) {
            $('#callback-output').prepend('movedFromCenter: ' + $item.attr('class') + '<br/>');
          },
          clickedCenter: function ($item) {
            $('#callback-output').prepend('clickedCenter: ' + $item.attr('class') + '<br/>');
          }
        });

        $('#prev').bind('click', function () {
          carousel.prev();
          return false
        });

        $('#next').bind('click', function () {
          carousel.next();
          return false;
        });

        $('#reload').bind('click', function () {
          newOptions = eval("(" + $('#newoptions').val() + ")");
          carousel.reload(newOptions);
          return false;
        });

      });
</script>

PixageStudioWeb/Views/Home/_HeaderPartial.cshtml
<style>

#header-style{
        margin-top:60px;
    }
    ul{
        padding: 0;
        list-style: none;
       
    }
    ul li{
        display: inline-block;
        position: relative;
        line-height: 21px;
        text-align: left;
    }
    ul li a{
        display: block;
        padding: 8px 25px;
        color: #333;
        text-decoration: none;
    }
    ul li a:hover{
        color: #fff;
        background: #939393;
    }
    ul li ul.dropdown{
        min-width: 100%; /* Set width of the dropdown */
        background: #f2f2f2;
        display: none;
        position: absolute;
        z-index: 999;
        left: 0;
    }
    ul li:hover ul.dropdown{
        display: block; /* Display the dropdown */
    }
    ul li ul.dropdown li{
        display: block;
    }
</style>
<nav class="col-md-12" id="header-style">
   

        <ul>
            <li class="active"><a href="@Url.Action("Index", "Home")">Home</a></li>
            <li>
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    Portfolio
                  
                </a>
              
                    <ul class="dropdown">
                        @foreach (Category item in ViewBag.Category)
                        {
                            <li style="width:100%;"><a href="@Url.Action("GetGenre", "Pages", new { id=item.Id})">@item.Name</a></li>
                        }
                    </ul>
                

            </li>
            <li><a href="@Url.Action("About", "Home")">About Us</a></li>
            <li><a href="@Url.Action("Contact", "Home")">Contact</a></li>
        </ul>
  
</nav>

PixageStudioWeb/Views/Home/_PortfolioPartial.cshtml
@model MultiModel
    @{
    ViewData["Title"] = "Images";
    Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <link rel="stylesheet" href="~/Plugin/style.css">
    <link rel="stylesheet" href="~/Plugin/ekko-lightbox.css">


    <div id="container">

        @foreach (var item in Model.images)
    {

        <div class="grid">
            <div class="imgholder">
                <a href="~/images/@Html.DisplayFor(modelItem=> item.AltName )" data-toggle="lightbox" data-gallery="example-gallery" class="col-md-12">
                    <img src="~/images/@Html.DisplayFor(modelItem=> item.AltName )" class="img-responsive">

                </a>

            </div>
        </div>



    }




    </div>

    @section scripts{
        <script src="~/Plugin/blocksit.js"></script>
        <script>
        $(document).ready(function () {
            //vendor script
            $('#header')
                .css({ 'top': -50 })
                .delay(1000)
                .animate({ 'top': 0 }, 800);

            $('#footer')
                .css({ 'bottom': -15 })
                .delay(1000)
                .animate({ 'bottom': 0 }, 800);

            //generate blocks
            var numOfClone = 20;
            for (var i = 0; i < numOfClone; i++) {
                var clone = $('#container').find('.block:first').clone();
                clone.attr('id', 'clone-' + i);
                clone.css('height', (Math.floor(Math.random() * 5) + 1) * 100);
                clone.attr('data-size', Math.floor(Math.random() * 3) + 1);

                $('#container').append(clone);
            }

            //blocksit define
            $('#container').BlocksIt({
                numOfCol: 7
            });
        });
        </script>
        <script src="~/Plugin/ekko-lightbox.js"></script>

    }

}
<style>
    ul {
        padding: 0;
        list-style: none;
        background: #f2f2f2;
    }

        ul li {
            display: inline-block;
            position: relative;
            line-height: 21px;
            text-align: left;
        }

            ul li a {
                display: block;
                padding: 8px 25px;
                color: #333;
                text-decoration: none;
            }

                ul li a:hover {
                    color: #fff;
                    background: #939393;
                }

            ul li ul.dropdown {
                min-width: 100%; /* Set width of the dropdown */
                background: #f2f2f2;
                display: none;
                position: absolute;
                z-index: 999;
                left: 0;
            }

            ul li:hover ul.dropdown {
                display: block; /* Display the dropdown */
            }

            ul li ul.dropdown li {
                display: block;
            }

    .navbar {
        margin-top: 60px;
    }




    .nav {
        margin-top: 0px;
        align-self: flex-end;
    }

    .footer {
        align-self: center;
    }
</style>

PixageStudioWeb/Views/Home/_RegisterPartial.cshtml
@model Login

<div id="form" style="min-width:350px;" class="pull-left">
    <div class="text-danger" asp-validation-summary="All"></div>
    <form asp-action="Register" asp-controller="Account" method="post" style="margin:5px 5px 5px 5px">
        <input type="hidden" asp-for="ReturnUrl" />
        <ul>
            <li>
                <label asp-for="Email"></label>
                <input asp-for="Email" class="col-md-6" />
            </li>


            <li>
                <label asp-for="Password"></label>
                <input type="password" asp-for="Password" class="col-md-6" />
            </li>
            <li>
                
            </li>
            <li>
                <button type="submit">Login</button>
                <label>
                    <input type="checkbox" checked="checked" name="remember"> Remember me
                </label>
            </li>
            <li>
                <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
                <span class="psw">Forgot <a href="#">password?</a></span>
            </li>
        </ul>
    </form>

</div>