PixageStudioWeb/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PixageStudioWeb.Data;
using PixageStudioWeb.Models;

namespace PixageStudioWeb.Controllers

{
    //[Authorize(Roles="Administrator, Editor")]
    public class AdminController : Controller
    {
        private  UserManager<ApplicationUser> _userManager;
        private IPasswordHasher<ApplicationUser> _passwordHasher;
        private readonly ApplicationDbContext _context;

        public AdminController(UserManager<ApplicationUser> usrMgr, IPasswordHasher<ApplicationUser> passwordHasher, ApplicationDbContext context )
        {
            _userManager = usrMgr;
            _passwordHasher = passwordHasher;
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.Users = _userManager.Users.ToList();
            return View();
        }
        public IActionResult UserRole()
        {
            return View();
        }
        public ViewResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(User user)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser appUser = new ApplicationUser
                {
                    UserName = user.Name,
                    Email = user.Email,
                    
                };
                try
                {
                    IdentityResult result = await _userManager.CreateAsync(appUser, user.Password);
                    if (result.Succeeded)
                        return RedirectToAction("Index");
                    else
                    {
                        //foreach (IdentityError error in result.Errors)
                        //    ModelState.AddModelError("", error.Description);
                        TempData["Message"] = "There was an error creating the user.";
                        return RedirectToAction("Index");

                    }
                }
                catch
                {
                    TempData["Message"] = "An Error Occured";
                }
            }
            return View(user);
        }
        public async Task<IActionResult> Update(string id)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
                return View(user);
            else
                return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Update(string id, string email, string password)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                if (!string.IsNullOrEmpty(email))
                    user.Email = email;
                else
                    ModelState.AddModelError("", "Email cannot be empty");

                if (!string.IsNullOrEmpty(password))
                    user.PasswordHash = _passwordHasher.HashPassword(user, password);
                else
                    ModelState.AddModelError("", "Password cannot be empty");

                if (!string.IsNullOrEmpty(email) && !string.IsNullOrEmpty(password))
                {
                    IdentityResult result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                        return RedirectToAction("Index");
                    else
                        Errors(result);
                }
            }
            else
                ModelState.AddModelError("", "User Not Found");
            return View(user);
        }

        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            else
                ModelState.AddModelError("", "User Not Found");
            return View("Index", _userManager.Users);
        }
       
        public IActionResult Dashboard()
        {
            return View();
        }
        public IActionResult Upload()
        {
            ViewBag.Categories = _context.Categories.ToList();
            return View();
        }
    }
}

PixageStudioWeb/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PixageStudioWeb.Data;
using PixageStudioWeb.Models;

namespace PixageStudioWeb.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            ViewBag.Category = await _context.Categories.ToListAsync();
            return View();
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

PixageStudioWeb/Controllers/ContentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PixageStudioWeb.Data;
using PixageStudioWeb.Models;

namespace PixageStudioWeb.Controllers
{
   // [Authorize(Roles="Administrator, Editor")]
    public class ContentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Contents
        public async Task<IActionResult> Index()
        {
            ViewBag.Category = await _context.Categories.Where(x => x.Name != "Homepage").OrderBy(x => x.Name).ToListAsync(); 
            ViewBag.Content = await _context.Content.ToListAsync();
            return View();
        }

        // GET: Contents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var content = await _context.Content
                .FirstOrDefaultAsync(m => m.Id == id);
            if (content == null)
            {
                return NotFound();
            }

            return View(content);
        }

        // GET: Contents/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Data,Category,FontName,FontSize")] Content content)
        {
            if (ModelState.IsValid)
            {
                _context.Add(content);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(content);
        }

        // GET: Contents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var content = await _context.Content.FindAsync(id);
            if (content == null)
            {
                return NotFound();
            }
            return View(content);
        }

        // POST: Contents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Data,Category,FontName,FontSize")] Content content)
        {
            if (id != content.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(content);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContentExists(content.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(content);
        }

        // GET: Contents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var content = await _context.Content
                .FirstOrDefaultAsync(m => m.Id == id);
            if (content == null)
            {
                return NotFound();
            }

            return View(content);
        }

        // POST: Contents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var content = await _context.Content.FindAsync(id);
            _context.Content.Remove(content);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContentExists(int id)
        {
            return _context.Content.Any(e => e.Id == id);
        }
    }
}

PixageStudioWeb/Views/Admin/Create.cshtml
@model User
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<h1 class="bg-info text-white">Create User</h1>
<a asp-action="Index" class="btn btn-secondary">Back</a>
<div asp-validation-summary="All" class="text-danger"></div>

<form method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Password"></label>
        <input asp-for="Password" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

PixageStudioWeb/Views/Admin/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        padding: 16px;
        text-align: center;
        background-color: #f1f1f1;
        height: 170px;
    }
    img{
        max-height:100px;
        max-width:100px;
    }
  .card:hover {
            background-color: gold;
        }

    .column {
        float: left;
        width: 25%;
        padding: 0 10px;
    }

    * {
        box-sizing: border-box;
    }

    .row {
        margin: 0 80px;
    }

        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }
</style>
<h2>Dashboard</h2>
<div class="container">

    <div class="row tab">

        <div class="column">
            <a href="@Url.Action("Index","Admin")">
                <div class="card">
                    Manage Users
                    <div id="icon"><img src="~/assets/ico/manage_users.png"></div>
                    <span class="glyphicon glyphicon-user"></span>
                </div>
            </a>
        </div>
        <div class="column">
            <a href="@Url.Action("Index", "ImagePools")">
                <div class="card">
                    <div id="icon"><img src="~/assets/ico/manage_gallery.png"></div>
                    Manage Galleries
                </div>
            </a>

        </div>
        <div class="column">
            <a href="@Url.Action("Create","Categories")">
                <div class="card">
                    Manage Content
                    <div id="icon"><img src="~/assets/ico/Manage_content.png"></div>
                </div>
            </a>

        </div>
        
    </div>
    <div class="row tab">
        <div class="column">
            <a href="@Url.Action("Index","Contents")">
                <div class="card">
                    Manage Content
                    <div id="icon"><img src="~/assets/ico/Manage_content.png"></div>
                </div>
            </a>

        </div>
    </div>

</div>

PixageStudioWeb/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1 class="bg-info text-white">All Users</h1>
<a asp-action="Create" class="btn btn-secondary">Create a User</a>

<table class="table table-sm table-bordered">
    <tr><th>ID</th><th>Name</th><th>Email</th></tr>
    @foreach (var user in ViewBag.Users)
    {
<tr>
    <td>@user.Id</td>
    <td>@user.UserName</td>
    <td>@user.Email</td>
    <td><a class="btn btn-sm btn-primary" asp-action="Update" asp-route-id="@user.Id">Update</a></td>
    <td>
        <form asp-action="Delete" asp-route-id="@user.Id" method="post">
            <button type="submit" class="btn btn-sm btn-danger">
                Delete
            </button>
        </form>
    </td>
</tr>
    }
</table>

PixageStudioWeb/Views/Admin/Update.cshtml
@model ApplicationUser
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h1 class="bg-info text-white">Update User</h1>
<a asp-action="Index" class="btn btn-secondary">Back</a>
<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Update" method="post">
    <div class="form-group">
        <label asp-for="Id"></label>
        <input asp-for="Id" class="form-control" disabled />
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input name="password" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

PixageStudioWeb/Views/Admin/Upload.cshtml
@{
    ViewData["Title"] = "Upload";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-3">
        <h5>Upload Images to your Genres Here</h5>

        <form asp-controller="ImagePools" asp-action="UploadFile" method="post"
              enctype="multipart/form-data">
            <div class="form-group"><input type="file" name="file" accept="image/*" /></div>
            <div class="form-group">
                <h6>Select Category</h6>
                <select name="Genre" class="form-control">
                    @foreach (Category cat in ViewBag.Categories)
                    {
                        <option value="@cat.Id">@cat.Name</option>
                    }


                </select>
            </div>
            <div class="form-group"><button type="submit">Upload Image</button></div>

        </form>
        <form method="post" asp-action="UploadMultiple" asp-controller="ImagePools" enctype="multipart/form-data">
            <div><input type="file" name="files" multiple /></div>
            <div class="form-group">
                <h6>Select Category</h6>
                <select name="Genre" class="form-control">
                    @foreach (Category cat in ViewBag.Categories)
                    {
                        <option value="@cat.Id">@cat.Name</option>
                    }


                </select>
            </div>
            <div>
                <input type="submit" value="Upload" />
            </div>
        </form>
        <form method="post" asp-action="UploadAboutPicture" asp-controller="ImagePools" enctype="multipart/form-data">
            <div><input type="file" name="file" accept="image/*" /></div>
            <div class="form-group">
                <h6>Select Category</h6>
                <select name="Genre" class="form-control">
                    
                        <option value="AboutUs">About Us</option>
                    


                </select>
            </div>
            <div>
                <input type="submit" value="Upload" />
            </div>
        </form>
    </div>

</div>